# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  #- mysql:latest
  - postgres:latest

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

# Cache gems in between builds
cache:
  paths:
    - vendor

before_script:
  - apt-get update -qy && apt-get install -y nodejs
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path /vendor
  # - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:grate

test:
  script:
  - bundle exec rspec

#staging:
#  type: deploy
#  script:
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
#  only:
#  - master

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
#production:
#  type: deploy
#  script:
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
#  - tags
