# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.4"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  #- mysql:latest
  - postgres:latest

variables:
  POSTGRES_DB: mrt_production

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby
    #- vendor
    
test:
  script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler --no-ri --no-rdoc    # Bundler is not installed with the image
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rspec

#staging:
#  type: deploy
#  script:
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
#  only:
#  - master

# This deploy job uses a simple deploy flow to Heroku, other providers, e.g. AWS Elastic Beanstalk
# are supported too: https://github.com/travis-ci/dpl
#production:
#  type: deploy
#  script:
#  - gem install dpl
#  - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
#  - tags
